# Generated by Django 3.1.3 on 2021-05-25 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arquivo',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
